const {test}=require('node:test');
const assert=require('node:assert/strict');
const {TranscriptStitcher,wordsFromTokens}=require('../src/features/common/ai/parakeet/transcriptStitcher');
const SR=16000,w=(text,start,end=start+.2)=>({text,start:Math.round(start*SR),end:Math.round(end*SR)});
const result=(id,words,start,end,coreEnd,final=false,extra={})=>({id,words,start:Math.round(start*SR),end:Math.round(end*SR),coreEnd:Math.round(coreEnd*SR),final,...extra});
function rendered(events){const spans=new Map();for(const e of events){for(const id of e.removeSpanIds||[])spans.delete(id);for(const c of e.commits)spans.set(c.spanId,c);}return [...spans.values()].sort((a,b)=>a.sourceStart-b.sourceStart).map(s=>s.text).join(' ');}
test('BPE tokens preserve words, punctuation, contractions and source times',()=>{const x=wordsFromTokens({tokens:[' I',"'",'ll',' re','ce','ive','.'],timestamps:[0,.1,.2,.3,.4,.5,.6],durations:Array(7).fill(.1)},SR);assert.deepEqual(x.map(w=>w.text),["I'll",'receive.']);assert.equal(x[0].start,SR);assert.equal(x[1].end,27200);});
test('numeric BPE pieces and standalone spaces use the raw result text',()=>{const x=wordsFromTokens({text:'need 12 an estimated one.',tokens:[' need','12',' an',' ','est','imated',' one','.'],timestamps:[0,.1,.2,.3,.4,.5,.6,.7]});assert.deepEqual(x.map(w=>w.text),['need','12','an','estimated','one.']);});
test('malformed token timing and source bounds are rejected',()=>{assert.throws(()=>wordsFromTokens({tokens:['hi'],timestamps:[]}),/timestamp/);const s=new TranscriptStitcher();assert.throws(()=>s.accept(result('a',[w('hi',5)],0,2,2,true)),/bounds/);assert.throws(()=>s.accept(result('a',[w('two',2),w('one',1)],0,3,3,true)),/order/);});

test('first observation displays all words provisionally, including the trailing edge',()=>{const s=new TranscriptStitcher();const e=s.accept(result('a',[w('order.',2.8,3)],0,3,3));assert.equal(e.text,'order.');assert.equal(e.commits[0].provisional,true);assert.equal(e.confirmationRequests,undefined);});
test('natural end is not finality while source audio remains retained',()=>{const s=new TranscriptStitcher();const e=s.accept(result('a',[w('hello',1)],0,3,3,true));assert.equal(e.commits[0].provisional,true);assert.equal(s.pending.length,1);});
test('deeper evidence immediately replaces a provisional span using the same ID',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('parties',2.5)],0,3,3));const b=s.accept(result('b',[w('parts',2.5)],0,6,6));assert.equal(a.commits[0].spanId,b.commits[0].spanId);assert.equal(b.text,'parts');assert.equal(b.commits[0].revision,2);assert.equal(b.commits[0].provisional,true);});
test('best edge distance wins even if the last arriving observation is weaker',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('parts',10)],0,19.5,19));const b=s.accept(result('b',[w('parties',10.05)],9.75,25,25));assert.equal(rendered([a,b,s.flush()]),'parts');});
test('source clock finalizes exactly at the 25-second retention age',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('hello',1,1.2)],0,3,3));assert.equal(s.advance(Math.round(26.2*SR)-1).commits.length,0);const e=s.advance(Math.round(26.2*SR));assert.equal(e.text,'hello');assert.equal(e.commits[0].provisional,false);assert.equal(s.pending.length,0);assert.equal(s.advance(27*SR).commits.length,0);});
test('silence alone advances finalization without another decoder result',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('hello',1)],0,3,3));const e=s.advance(40*SR);assert.equal(e.commits.length,1);assert.equal(e.commits[0].provisional,false);});
test('late decoder output cannot alter a finalized span or resurrect a duplicate',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('parts',1)],0,3,3));const f=s.advance(27*SR);const b=s.accept(result('late',[w('parties',1.05)],0,10,10,false,{observation:true,sourceClock:27*SR}));assert.equal(rendered([a,f,b]),'parts');assert.equal(b.commits.length,0);});
test('stop settles every displayed tail then rejects further observations',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('order.',2.8,3)],0,3,3));const e=s.flush();assert.equal(e.text,'order.');assert.equal(e.commits[0].provisional,false);assert.equal(s.pending.length,0);assert.equal(s.flush().commits.length,0);assert.throws(()=>s.accept(result('b',[],0,6,6)),/closed/);});
test('a dispute never blocks provisionals before or after its own span',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('delivery',1),w('as',2.5),w('complete',2.8)],0,3,3));const e=s.accept(result('b',[w('delivery',1),w('is',2.5),w('complete',2.8),w('before',4)],0,6,6));assert.match(e.text,/is complete before/);assert.ok(e.commits.every(c=>c.provisional));});
test('a covered omission does not silently erase the best known negation',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('do',1),w('not',2)],0,3,3));const b=s.accept(result('b',[w('do',1),w('cancel',4)],0,6,6));assert.equal(rendered([a,b,s.flush()]),'do not cancel');});
test('split and merged alternatives are atomic replacements, not duplicate suffixes',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('can',2.4,2.6),w('not',2.6,2.8)],0,3,3));const b=s.accept(result('b',[w('cannot',2.4,2.8)],0,6,6));assert.equal(rendered([a,b]),'cannot');assert.equal(b.removeSpanIds.length,1);assert.equal(b.commits[0].provisional,true);});
test('a matching prefix does not discard the rest of a split hypothesis',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w("can't",2.4,2.8)],0,3,3));const b=s.accept(result('b',[w('can',2.4,2.8)],0,4,4));const c=s.accept(result('c',[w('can',2.4,2.6),w('not',2.6,2.8)],0,6,6));assert.equal(rendered([a,b,c]),'can not');});
test('repeated words retain distinct occurrence IDs through revisions',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('very',1),w('very',1.3)],0,3,3));const b=s.accept(result('b',[w('very',1.05),w('very',1.35),w('very',4)],0,6,6));assert.equal(rendered([a,b,s.flush()]),'very very very');});
test('duplicate result IDs do not produce duplicate provisional events',()=>{const s=new TranscriptStitcher(),r=result('a',[w('hi',1)],0,3,3);s.accept(r);assert.equal(s.accept(r).duplicate,true);assert.throws(()=>s.accept(result('b',[],0,2,2)),/order/);});
test('invalid future source clocks and word bounds do not age existing spans',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('hi',1)],0,3,3));assert.throws(()=>s.accept(result('b',[w('bad',40)],0,6,6,false,{sourceClock:40*SR})),/bounds/);assert.equal(s.pending.length,1);assert.throws(()=>s.accept(result('c',[],0,6,6,false,{sourceClock:4*SR})),/clock/);assert.throws(()=>s.advance(2*SR),/clock/);});
test('settled anchors prevent timestamp drift from reopening a word at the cutoff',()=>{const s=new TranscriptStitcher();const a=s.accept(result('a',[w('not',1,1.2)],0,3,3));const f=s.advance(Math.round(26.2*SR));const b=s.accept(result('late',[w('knot',1.1,1.4)],0,10,10,false,{observation:true,sourceClock:Math.round(26.2*SR)}));assert.equal(rendered([a,f,b]),'not');assert.equal(s.pending.length,0);});

test('a late natural completion may reanalyse a zero-new-audio final context',()=>{const s=new TranscriptStitcher();s.accept(result('a',[w('order',2)],0,3,3));assert.doesNotThrow(()=>s.accept(result('b',[w('order.',2)],0,3,3,true,{coreStart:3*SR,sourceClock:4*SR})));assert.ok(s.pending.every(w=>w.provisional));assert.throws(()=>s.accept(result('c',[],0,3,3,false,{coreStart:3*SR})),/order/);});
